# Generated by Django 5.1.2 on 2024-11-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=25, null=True)),
                ('maximum_companions', models.PositiveIntegerField(default=0)),
                ('token', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('WFC', 'Waiting for confirmation'), ('C', 'Confirmed'), ('R', 'Refused')], default='WFC', max_length=3)),
            ],
        ),
    ]
