# Generated by Django 5.1.2 on 2024-11-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom', '0002_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groom.guests'),
        ),
    ]
