"""Smoke tests for the groom app and the cross-app guests views.

These cover the core behaviour of the wedding registry and the bugs the
robustness pass fixed: bad invitation tokens must return 404 (not 500),
an already-reserved gift cannot be re-reserved, and missing/invalid POST
fields must not crash the gift/guest creation views.
"""

from django.test import TestCase
from django.urls import reverse

from groom.models import Gifts, Guests


class HomeViewTests(TestCase):
    def test_home_get_returns_200(self):
        response = self.client.get(reverse('home'))
        self.assertEqual(response.status_code, 200)

    def test_root_redirects_to_groom(self):
        response = self.client.get('/')
        self.assertRedirects(
            response, '/groom/', fetch_redirect_response=False
        )

    def test_gift_post_creates_row(self):
        self.assertEqual(Gifts.objects.count(), 0)
        self.client.post(
            reverse('home'),
            {'gift_name': 'Blender', 'price': '99.90', 'significance': '3'},
        )
        self.assertEqual(Gifts.objects.count(), 1)
        gift = Gifts.objects.get()
        self.assertEqual(gift.gift_name, 'Blender')
        self.assertEqual(gift.significance, 3)

    def test_gift_post_missing_significance_does_not_crash(self):
        # Previously int(None) raised TypeError -> HTTP 500.
        response = self.client.post(
            reverse('home'), {'gift_name': 'No significance', 'price': '10'}
        )
        self.assertEqual(response.status_code, 302)
        self.assertEqual(Gifts.objects.count(), 0)

    def test_gift_post_out_of_range_significance_rejected(self):
        self.client.post(
            reverse('home'),
            {'gift_name': 'Too important', 'price': '10', 'significance': '9'},
        )
        self.assertEqual(Gifts.objects.count(), 0)


class GuestsListViewTests(TestCase):
    def test_guests_list_get_returns_200(self):
        response = self.client.get(reverse('guests_list'))
        self.assertEqual(response.status_code, 200)

    def test_guest_post_creates_row_with_token(self):
        self.client.post(
            reverse('guests_list'),
            {'guest_name': 'Ana', 'whatsapp': '1234', 'maximum_companions': '2'},
        )
        self.assertEqual(Guests.objects.count(), 1)
        guest = Guests.objects.get()
        self.assertTrue(guest.token)  # auto-generated on save
        self.assertEqual(guest.maximum_companions, 2)

    def test_guest_post_missing_companions_defaults_to_zero(self):
        # Previously int(None) raised TypeError -> HTTP 500.
        response = self.client.post(
            reverse('guests_list'), {'guest_name': 'Bob'}
        )
        self.assertEqual(response.status_code, 302)
        self.assertEqual(Guests.objects.get().maximum_companions, 0)


class ModelTests(TestCase):
    def test_token_autogenerated_and_unique(self):
        g1 = Guests.objects.create(guest_name='One')
        g2 = Guests.objects.create(guest_name='Two')
        self.assertTrue(g1.token)
        self.assertNotEqual(g1.token, g2.token)

    def test_link_invitation_uses_site_url(self):
        guest = Guests.objects.create(guest_name='Carol')
        self.assertIn(f'token={guest.token}', guest.link_invitation)
        self.assertTrue(guest.link_invitation.startswith('http'))


class InvitationFlowTests(TestCase):
    def setUp(self):
        self.guest = Guests.objects.create(guest_name='Dora')
        self.gift = Gifts.objects.create(
            gift_name='Toaster', price='49.90', significance=3
        )

    def test_invalid_token_returns_404_not_500(self):
        response = self.client.get('/guests/?token=does-not-exist')
        self.assertEqual(response.status_code, 404)

    def test_valid_token_returns_200(self):
        response = self.client.get(f'/guests/?token={self.guest.token}')
        self.assertEqual(response.status_code, 200)

    def test_answer_attendance_updates_status(self):
        self.client.get(
            f'/guests/answer_attendance/?answer=C&token={self.guest.token}'
        )
        self.guest.refresh_from_db()
        self.assertEqual(self.guest.status, 'C')

    def test_reserve_gift_marks_reserved(self):
        self.client.get(
            f'/guests/reserve_gift/{self.gift.id}?token={self.guest.token}'
        )
        self.gift.refresh_from_db()
        self.assertTrue(self.gift.reserved)
        self.assertEqual(self.gift.reserved_by, self.guest)

    def test_already_reserved_gift_cannot_be_stolen(self):
        other = Guests.objects.create(guest_name='Eve')
        self.gift.reserved = True
        self.gift.reserved_by = self.guest
        self.gift.save()

        self.client.get(
            f'/guests/reserve_gift/{self.gift.id}?token={other.token}'
        )
        self.gift.refresh_from_db()
        # The original reserver must be preserved.
        self.assertEqual(self.gift.reserved_by, self.guest)
